name: Docker Build

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:

  build-frontend:
    uses: localagi/ai-dedicated-workflows/.github/workflows/operation-docker-build-publish.yml@v1
    with:
      registry-dockerhub-enable: false
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64/v8
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
